// Villa Cortese — content + i18n
// Local images live under /images. Slots not yet replaced fall back to the
// original WordPress URLs so every spot still renders.
window.VC_PHOTOS = {
  hero: "images/hero.jpg",
  exterior: "images/welcome.jpg",
  garden: "https://www.villacorteseclusone.it/wp-content/uploads/2026/01/Esterni_iris-768x1024.jpg",
  basilica: "https://www.villacorteseclusone.it/wp-content/uploads/2024/01/Basilica-2.jpg",
  outdoor: "https://www.villacorteseclusone.it/wp-content/uploads/2024/03/IMG_7350.jpg",
  living: "images/breakfast/breakfast_4.jpg",
  living2: "https://www.villacorteseclusone.it/wp-content/uploads/2024/01/IMG_0456-1-768x1024.jpg",
  doppiaNord: "images/rooms/cortese.jpg",
  doppiaNord2: "https://www.villacorteseclusone.it/wp-content/uploads/2024/01/Doppia_Nord_2-1-768x1024.jpg",
  doppiaNord3: "https://www.villacorteseclusone.it/wp-content/uploads/2024/01/Doppia_Nord_3-768x1024.jpg",
  doppiaNordBath: "https://www.villacorteseclusone.it/wp-content/uploads/2024/01/Doppia_Nord_B-768x1024.jpg",
  bagno: "https://www.villacorteseclusone.it/wp-content/uploads/2024/01/IMG_8640-768x1024.jpg",
  triplaDeluxe: "images/rooms/iris.jpg",
  triplaDeluxe2: "https://www.villacorteseclusone.it/wp-content/uploads/2026/01/Tripla_new1-768x1024.jpg",
  doppiaSud: "images/rooms/pizzo.jpg",
  colazione1: "images/breakfast/breakfast_hero.jpg",
  colazione2: "images/breakfast/breakfast_1.jpg",
  colazione3: "images/breakfast/breakfast_2.jpg",
  colazione4: "images/breakfast/breakfast_3.jpg",
  bagno2: "https://www.villacorteseclusone.it/wp-content/uploads/2024/01/IMG_9761.jpg",
};

window.VC_I18N = {
  it: {
    nav: {
      story: "Storia",
      rooms: "Camere",
      location: "Dove Siamo",
      outdoor: "Outdoor",
      weddings: "Matrimoni",
      contact: "Contatti",
      book: "Prenota",
    },
    hero: {
      meta_left: "B&B · Clusone · Val Seriana",
      meta_right_1: "Dimora storica",
      meta_right_2: "Anno mcmxxx",
      title_a: "Villa",
      title_b: "Cortese",
      sub: "Una dimora del 1930 immersa nel verde della Val Seriana, dove la quiete delle Prealpi Orobie incontra l'arte del ricevere.",
      scroll: "Scorri per scoprire",
    },
    marquee: ["Sport", "Relax", "Natura", "Cultura", "Ospitalità", "Dimora del 1930"],
    welcome: {
      num: "I.",
      eyebrow: "Benvenuti",
      title_a: "A due passi",
      title_b: "dal centro,",
      title_c: "lontano",
      title_d: "dal mondo.",
      lede: "Ai piedi delle Prealpi Orobie, Villa Cortese è una dimora storica restaurata con cura, a 200 metri dal cuore di Clusone. Tre camere, un giardino segreto, una colazione che racconta la valle.",
      body_1: "Quattro generazioni della famiglia Cortese hanno abitato questa casa dal 1930. Oggi Carlotta e suo padre Marco vi accolgono in un B&B a gestione familiare, dove ogni dettaglio porta con sé una storia — dalle pareti in legno originali alle nuove dotazioni pensate per chi cerca sport, relax, natura e cultura.",
      body_2: "Una posizione strategica per esplorare la Val Seriana, il Lago d'Iseo e Bergamo. E al ritorno, il piacere di una casa.",
      caption: "La veranda — fotografia, primavera 2024",
    },
    facts: [
      { num: "1930", label: "Anno di costruzione" },
      { num: "iv", label: "Generazioni in famiglia" },
      { num: "iii", label: "Camere ristrutturate" },
      { num: "200m", label: "Dal centro storico" },
    ],
    rooms: {
      num: "II.",
      eyebrow: "Le Camere",
      title_a: "Tre stanze,",
      title_b: "tre carattere.",
      lede: "Ogni camera porta il nome di un luogo o di un fiore della valle. Tutte al primo piano, tutte con bagno privato, tutte ristrutturate mantenendo l'anima della villa.",
      list: [
        {
          name_a: "Iris",
          type: "Camera Tripla Deluxe",
          desc: "La più ampia, con balcone affacciato sul giardino. Letto matrimoniale king size, letto singolo, possibilità di lettino per bambini fino a 3 anni.",
          feat: ["3 ospiti", "Balcone", "Letto king", "Bagno walk-in"],
        },
        {
          name_a: "Pizzo",
          type: "Camera Doppia con Balcone",
          desc: "Dedicata alla Presolana, la regina delle Orobie. Pareti in legno originali, terrazzino privato, vista sui giardini delle ville d'epoca.",
          feat: ["2 ospiti", "Balcone", "Pareti in legno", "Sud"],
        },
        {
          name_a: "Cortese",
          type: "Camera Doppia",
          desc: "Raccolta ed elegante, porta il nome della famiglia. Atmosfera intima, dotata di ogni comfort, ideale per un soggiorno breve o una fuga di coppia.",
          feat: ["2 ospiti", "Bagno filo-pavimento", "Nord", "Smart TV"],
        },
      ],
      amenities_title: "Dotazioni",
      amenities: [
        "Bagno privato — doccia walk-in",
        "Asciugacapelli con diffusore",
        "Smart TV 32\" — Netflix, Prime Video",
        "Cuscini Silver anallergici",
        "Wi-Fi alta velocità",
        "Prodotti da bagno in omaggio",
      ],
    },
    breakfast: {
      num: "III.",
      eyebrow: "La Colazione",
      title_a: "Un rito",
      title_b: "del mattino.",
      lede: "Servita nel living a piano terra, o nel giardino quando il tempo lo concede. Buffet dolce e salato, torte e biscotti fatti in casa, prodotti locali, caffè in grani. Su richiesta gluten free e vegan.",
    },
    story: {
      num: "IV.",
      eyebrow: "Storia",
      title_a: "Costruita nel 1930.",
      title_b: "Abitata,",
      title_c: "amata, custodita.",
      quote: "«La villa è ancora abitata dalla famiglia Cortese. Quattro generazioni hanno camminato sulle scale che oggi portano alle vostre camere.»",
      timeline: [
        { y: "1930", t: "L'ingegner Vincenzo Cortese progetta e costruisce la villa nel quartiere residenziale a sud del centro storico di Clusone." },
        { y: "1960s", t: "La famiglia si stabilisce definitivamente. Il giardino prende la sua forma attuale, con gli iris e le rose che ancora oggi accolgono gli ospiti." },
        { y: "2010", t: "Avvio del progetto di valorizzazione. Studio dei materiali originali, archivio fotografico, restauro conservativo della facciata." },
        { y: "2024", t: "Riapertura come B&B dopo l'ultima ristrutturazione. Impianto fotovoltaico, tre camere ristrutturate, anima invariata." },
      ],
    },
    location: {
      num: "V.",
      eyebrow: "Dove Siamo",
      title_a: "Clusone,",
      title_b: "Val Seriana.",
      lede: "Via Garibaldi 1, all'ombra delle Prealpi Orobie. Cinque minuti a piedi dalla Basilica e dall'Orologio Fanzago, due minuti dalla stazione degli autobus.",
      sights: [
        { num: "i", name_a: "Centro storico di Clusone", dist: "200 m" },
        { num: "ii", name_a: "Basilica di Santa Maria Assunta", dist: "5 min" },
        { num: "iii", name_a: "Pizzo della Presolana", dist: "20 km" },
        { num: "iv", name_a: "Lago d'Iseo", dist: "35 km" },
        { num: "v", name_a: "Bergamo Alta", dist: "45 km" },
        { num: "vi", name_a: "Aeroporto di Orio al Serio", dist: "55 km" },
      ],
    },
    outdoor: {
      num: "VI.",
      eyebrow: "Outdoor & Inverno",
      title_a: "La valle,",
      title_b: "in ogni stagione.",
      lede: "Asciuga-scarponi professionale, deposito sci, garage chiuso per bici e moto, ricarica e-bike, lavaggio bici. Carlotta consiglia gli itinerari, dalle ferrate alle ciaspolate.",
      cards: [
        { num: "i", label_a: "Trekking", sub: "& Ferrate", which: "lg" },
        { num: "ii", label_a: "Cicloturismo", sub: "MTB & E-bike", which: "md" },
        { num: "iii", label_a: "Scialpinismo", sub: "Inverno", which: "sq" },
        { num: "iv", label_a: "Lago d'Iseo", sub: "30 minuti", which: "sq" },
        { num: "v", label_a: "Vette delle Orobie", sub: "Pizzo della Presolana — Monte Pora — Cima di Grem", which: "wide" },
      ],
    },
    weddings: {
      eyebrow: "Speciale Matrimoni",
      num: "VII.",
      title_a: "Per il giorno",
      title_b: "più importante.",
      intro: "Se stai organizzando il tuo matrimonio a Clusone o in Val Seriana e cerchi una struttura elegante e tranquilla dove far soggiornare i tuoi invitati, B&B Villa Cortese è una soluzione ideale.",
      note: "Non siamo una location per matrimoni, ma un B&B di charme pensato per accogliere gli ospiti del tuo giorno speciale in un contesto riservato, curato e facilmente raggiungibile.",
      cta: "Richiedi disponibilità",
      capacity_title: "La struttura",
      capacity: "La capienza massima è di 7 ospiti (+ neonato), distribuiti nelle tre camere. È possibile concordare una tariffa agevolata in caso di prenotazione dell'intera struttura.",
      services_title: "Servizi dedicati",
      services: [
        { icon: "◎", label: "Check-in anticipato", desc: "Su richiesta, per prepararsi con calma prima della cerimonia o del ricevimento." },
        { icon: "◎", label: "Tariffa struttura intera", desc: "Sconto concordato per chi prenota tutte e tre le camere per il weekend del matrimonio." },
        { icon: "◎", label: "Colazione personalizzata", desc: "Orario flessibile il giorno dopo, per recuperare le energie dopo i festeggiamenti." },
        { icon: "◎", label: "Atmosfera riservata", desc: "Una villa privata, lontana dal caos, a pochi passi dalle location della Val Seriana." },
      ],
      venues_title: "Location vicine",
      venues: [
        { name: "Agriturismo Larice", dist: "5 min in auto", desc: "Tra le location per ricevimenti più apprezzate della zona." },
        { name: "Ristorante La Bussola", dist: "5 min in auto", desc: "Cucina del territorio, spazi eleganti per banchetti." },
        { name: "Basilica di S. Maria Assunta", dist: "5 min a piedi", desc: "Una delle più belle chiese della Val Seriana, ideale per la cerimonia." },
      ],
      form_title: "Richiesta matrimonio",
      form_sub: "Raccontaci il vostro giorno speciale. Vi risponderemo entro 24 ore.",
      f_name: "Sposi (nome e cognome)",
      f_email: "Email",
      f_phone: "Telefono",
      f_date: "Data del matrimonio",
      f_checkin: "Check-in",
      f_checkout: "Check-out",
      f_nights: "Numero di notti",
      f_guests: "Numero di ospiti",
      f_rooms: "Camere richieste",
      f_rooms_opts: ["Tutta la struttura (7 ospiti)", "Camera Iris (tripla)", "Camera Pizzo (doppia)", "Camera Cortese (doppia)", "Da concordare"],
      f_notes: "Note aggiuntive",
      f_notes_ph: "Location del ricevimento, orario cerimonia, esigenze particolari…",
      f_submit: "Invia richiesta",
      sent_title: "Richiesta inviata.",
      sent_sub: "Carlotta vi risponderà entro 24 ore con disponibilità e tariffe dedicate.",
    },
    reviews: {
      num: "VII.",
      eyebrow: "Le voci degli ospiti",
      title_a: "Ciò che dicono",
      title_b: "di noi.",
    },
    booking: {
      num: "VIII.",
      eyebrow: "Richiesta disponibilità",
      title_a: "Una richiesta",
      title_b: "personale.",
      lede: "Non un portale, non un'algoritmo. Scrivete a Carlotta: vi risponderà entro 24 ore con disponibilità, tariffe e suggerimenti su misura.",
      checkin: "Check-in",
      checkout: "Check-out",
      guests: "Ospiti",
      room: "Camera",
      submit: "Invia richiesta",
      any: "qualsiasi",
      adults: "adulti",
      modal_title: "Richiesta disponibilità",
      modal_sub: "Compila il modulo: scriviamo personalmente.",
      name: "Nome e cognome",
      email: "Email",
      phone: "Telefono",
      notes: "Note (opzionale)",
      notes_placeholder: "Esigenze particolari, motivo del viaggio…",
      sent_title: "Richiesta inviata.",
      sent_sub: "Carlotta vi risponderà entro 24 ore.",
    },
    contact: {
      num: "IX.",
      eyebrow: "Contatti",
      title_a: "Scriveteci,",
      title_b: "telefonateci.",
      tel: "Telefono",
      tel_v: "+39 349 41 75 300",
      tel_meta: "Carlotta — preferibilmente WhatsApp",
      em: "Email",
      em_v: "villacortese1930@gmail.com",
      em_meta: "Risposta entro 24 ore",
      addr: "Indirizzo",
      addr_v: "Via Garibaldi, 1",
      addr_meta: "Clusone — Bergamo",
    },
    footer: {
      tag: "Una dimora del 1930.",
      explore: "Esplora",
      contact: "Contatti",
      legal: "Legale",
      cir: "CIR 016077-BEB-00009",
      cin: "CIN IT016077C1VDLX9FGD",
      copy: "© 2026 B&B Villa Cortese — Via Garibaldi 1, Clusone (BG)",
      credit: "Made with care, in Val Seriana.",
    },
  },
  en: {
    nav: { story: "Story", rooms: "Rooms", location: "Where", outdoor: "Outdoor", weddings: "Weddings", contact: "Contact", book: "Book" },
    hero: {
      meta_left: "B&B · Clusone · Val Seriana",
      meta_right_1: "A 1930 villa",
      meta_right_2: "Anno mcmxxx",
      title_a: "Villa",
      title_b: "Cortese",
      sub: "A 1930s residence in the heart of Val Seriana, where the quiet of the Orobic Pre-Alps meets the art of hosting.",
      scroll: "Scroll to discover",
    },
    marquee: ["Sport", "Relax", "Nature", "Culture", "Hospitality", "Built in 1930"],
    welcome: {
      num: "I.",
      eyebrow: "Welcome",
      title_a: "A few steps",
      title_b: "from the center,",
      title_c: "miles",
      title_d: "from the world.",
      lede: "At the foot of the Orobic Pre-Alps, Villa Cortese is a carefully restored historic residence, 200 meters from the heart of Clusone. Three rooms, a secret garden, a breakfast that tells the story of the valley.",
      body_1: "Four generations of the Cortese family have lived in this house since 1930. Today Carlotta and her father Marco welcome you to a family-run B&B, where every detail carries a story — from the original wood panels to the new amenities for those seeking sport, relaxation, nature and culture.",
      body_2: "A strategic location for exploring Val Seriana, Lake Iseo and Bergamo. And on returning, the pleasure of a home.",
      caption: "The veranda — photograph, spring 2024",
    },
    facts: [
      { num: "1930", label: "Year built" },
      { num: "iv", label: "Family generations" },
      { num: "iii", label: "Restored rooms" },
      { num: "200m", label: "From the old town" },
    ],
    rooms: {
      num: "II.",
      eyebrow: "The Rooms",
      title_a: "Three rooms,",
      title_b: "three characters.",
      lede: "Each room is named after a place or flower of the valley. All on the first floor, all with private bath, all restored while keeping the soul of the villa intact.",
      list: [
        { name_a: "Iris", type: "Triple Deluxe Room", desc: "The largest, with a balcony onto the garden. King-size double bed, single bed, optional crib for children up to 3 years.", feat: ["3 guests", "Balcony", "King bed", "Walk-in bath"] },
        { name_a: "Pizzo", type: "Double Room with Balcony", desc: "Named after the Presolana, queen of the Orobie. Original wood panels, private terrace, view onto the gardens of the period villas.", feat: ["2 guests", "Balcony", "Wood panels", "South"] },
        { name_a: "Cortese", type: "Double Room", desc: "Intimate and elegant, named after the family. A quiet atmosphere, every comfort, ideal for a short stay or a couple's escape.", feat: ["2 guests", "Curbless shower", "North", "Smart TV"] },
      ],
      amenities_title: "Amenities",
      amenities: ["Private bath — walk-in shower", "Hairdryer with diffuser", "32\" Smart TV — Netflix, Prime", "Hypoallergenic Silver pillows", "High-speed Wi-Fi", "Complimentary toiletries"],
    },
    breakfast: { num: "III.", eyebrow: "Breakfast", title_a: "A morning", title_b: "ritual.", lede: "Served in the ground-floor living room, or in the garden when weather permits. Sweet and savoury buffet, homemade cakes and biscuits, local produce, bean-to-cup coffee. Gluten-free and vegan options on request." },
    story: {
      num: "IV.",
      eyebrow: "Story",
      title_a: "Built in 1930.",
      title_b: "Lived in,",
      title_c: "loved, kept.",
      quote: "«The villa is still home to the Cortese family. Four generations have walked the stairs that today lead to your rooms.»",
      timeline: [
        { y: "1930", t: "Engineer Vincenzo Cortese designs and builds the villa in the residential quarter south of Clusone's old town." },
        { y: "1960s", t: "The family settles permanently. The garden takes its current form, with the irises and roses that still welcome guests today." },
        { y: "2010", t: "The conservation project begins. Study of original materials, photographic archive, restoration of the façade." },
        { y: "2024", t: "Reopening as a B&B after the latest renovation. Photovoltaic system, three restored rooms, soul unchanged." },
      ],
    },
    location: {
      num: "V.", eyebrow: "Where We Are", title_a: "Clusone,", title_b: "Val Seriana.",
      lede: "Via Garibaldi 1, in the shadow of the Orobic Pre-Alps. Five minutes' walk from the Basilica and the Fanzago clock, two minutes from the bus station.",
      sights: [
        { num: "i", name_a: "Clusone old town", dist: "200 m" },
        { num: "ii", name_a: "Basilica di Santa Maria Assunta", dist: "5 min" },
        { num: "iii", name_a: "Pizzo della Presolana", dist: "20 km" },
        { num: "iv", name_a: "Lake Iseo", dist: "35 km" },
        { num: "v", name_a: "Bergamo Alta", dist: "45 km" },
        { num: "vi", name_a: "Orio al Serio Airport", dist: "55 km" },
      ],
    },
    outdoor: {
      num: "VI.", eyebrow: "Outdoor & Winter", title_a: "The valley,", title_b: "in every season.",
      lede: "Professional boot dryer, ski storage, locked garage for bikes and motorcycles, e-bike charging, bike wash. Carlotta advises on routes, from via ferratas to snowshoeing.",
      cards: [
        { num: "i", label_a: "Trekking", sub: "& Via ferratas", which: "lg" },
        { num: "ii", label_a: "Cycling", sub: "MTB & E-bike", which: "md" },
        { num: "iii", label_a: "Ski touring", sub: "Winter", which: "sq" },
        { num: "iv", label_a: "Lake Iseo", sub: "30 minutes", which: "sq" },
        { num: "v", label_a: "Peaks of the Orobie", sub: "Pizzo della Presolana — Monte Pora — Cima di Grem", which: "wide" },
      ],
    },
    weddings: {
      eyebrow: "Wedding Special",
      num: "VII.",
      title_a: "For the most",
      title_b: "important day.",
      intro: "If you're planning your wedding in Clusone or Val Seriana and need an elegant, tranquil place for your guests to stay, B&B Villa Cortese is the ideal choice.",
      note: "We are not a wedding venue, but a charming B&B designed to host your guests in a private, well-kept setting — easily reachable from all the local reception venues.",
      cta: "Request availability",
      capacity_title: "The property",
      capacity: "Maximum capacity is 7 guests (+ infant) across three rooms. A preferential rate is available when booking the entire property for a wedding weekend.",
      services_title: "Dedicated services",
      services: [
        { icon: "◎", label: "Early check-in", desc: "On request — so guests can get ready at their own pace before the ceremony." },
        { icon: "◎", label: "Full-property rate", desc: "Discounted rate when all three rooms are booked together for the wedding weekend." },
        { icon: "◎", label: "Flexible breakfast", desc: "We adapt breakfast time the morning after, to let everyone recover at their own pace." },
        { icon: "◎", label: "Private atmosphere", desc: "A private villa, away from the bustle, moments from the valley's finest venues." },
      ],
      venues_title: "Nearby venues",
      venues: [
        { name: "Agriturismo Larice", dist: "5 min by car", desc: "One of the most appreciated reception venues in the area." },
        { name: "Ristorante La Bussola", dist: "5 min by car", desc: "Local cuisine, elegant spaces for banquets." },
        { name: "Basilica di S. Maria Assunta", dist: "5 min on foot", desc: "One of the finest churches in Val Seriana, ideal for the ceremony." },
      ],
      form_title: "Wedding enquiry",
      form_sub: "Tell us about your special day. We'll reply within 24 hours.",
      f_name: "Couple's names",
      f_email: "Email",
      f_phone: "Phone",
      f_date: "Wedding date",
      f_checkin: "Check-in",
      f_checkout: "Check-out",
      f_nights: "Number of nights",
      f_guests: "Number of guests",
      f_rooms: "Rooms requested",
      f_rooms_opts: ["Entire property (7 guests)", "Room Iris (triple)", "Room Pizzo (double)", "Room Cortese (double)", "To be discussed"],
      f_notes: "Additional notes",
      f_notes_ph: "Reception venue, ceremony time, special requirements…",
      f_submit: "Send enquiry",
      sent_title: "Enquiry sent.",
      sent_sub: "Carlotta will reply within 24 hours with availability and dedicated rates.",
    },
    reviews: { num: "VII.", eyebrow: "Guest voices", title_a: "What guests", title_b: "are saying." },
    booking: {
      num: "VIII.", eyebrow: "Availability request", title_a: "A personal", title_b: "enquiry.",
      lede: "Not a portal, not an algorithm. Write to Carlotta — she'll reply within 24 hours with availability, rates and tailored suggestions.",
      checkin: "Check-in", checkout: "Check-out", guests: "Guests", room: "Room", submit: "Send enquiry", any: "any", adults: "adults",
      modal_title: "Availability request", modal_sub: "Fill in the form — we reply personally.",
      name: "Full name", email: "Email", phone: "Phone", notes: "Notes (optional)", notes_placeholder: "Special needs, reason for travel…",
      sent_title: "Enquiry sent.", sent_sub: "Carlotta will reply within 24 hours.",
    },
    contact: {
      num: "IX.", eyebrow: "Contact", title_a: "Write,", title_b: "or call us.",
      tel: "Phone", tel_v: "+39 349 41 75 300", tel_meta: "Carlotta — WhatsApp preferred",
      em: "Email", em_v: "villacortese1930@gmail.com", em_meta: "Reply within 24 hours",
      addr: "Address", addr_v: "Via Garibaldi, 1", addr_meta: "Clusone — Bergamo",
    },
    footer: { tag: "A residence from 1930.", explore: "Explore", contact: "Contact", legal: "Legal", cir: "CIR 016077-BEB-00009", cin: "CIN IT016077C1VDLX9FGD", copy: "© 2026 B&B Villa Cortese — Via Garibaldi 1, Clusone (BG)", credit: "Made with care, in Val Seriana." },
  },
};

window.VC_REVIEWS = [
  { quote: "Struttura moolto bella, dentro e fuori, curata nei minimi dettagli. La colazione è varia ed abbondante, con prodotti fatti in casa e di qualità.", author: "Nadia", date: "Gen 2026", stars: "★★★★★" },
  { quote: "Eccellente. Ristrutturata con cura per ogni singolo dettaglio. L'accoglienza è stata cortese e calorosa.", author: "Francesco A.", date: "Gen 2026", stars: "★★★★★" },
  { quote: "Amazing location for both culture and nature aficionados. With the Orobic Alps at your doorstep, Villa Cortese serves whatever holiday you have in mind.", author: "Oscar J. Poiesz", date: "Dic 2024", stars: "★★★★★" },
];
